language: go

go:
  - 1.5.4
  - 1.6

services:
  - redis-server
  - docker

install:
  - make dependencies

script:
  - make stat test

after_success:
  - make clean
  - make docker
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag unixvoid/beacon unixvoid/beacon:develop
  - docker push unixvoid/beacon:develop
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/beacon*` --form path=beacon/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/beacon*` --form filename=beacon-latest-linux-amd64 --form path=beacon/ https://cryo.unixvoid.com/upload
  - curl -d sec=$BINDER_SEC -d key=unixvoid.pub https://cryo.unixvoid.com/getfile --output unixvoid.pub
  - curl -d sec=$BINDER_SEC -d key=unixvoid.sec https://cryo.unixvoid.com/getfile --output unixvoid.sec
  - make clean travisaci
  - mv beacon.aci beacon-latest-linux-amd64.aci
  - cp deps/sign.sh . && chmod +x sign.sh
  - ./sign.sh $GPG_SEC
  - curl -i --form sec=$BINDER_SEC --form file=@beacon-latest-linux-amd64.aci --form path=rkt/beacon/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@beacon-latest-linux-amd64.aci.asc --form path=rkt/beacon/ https://cryo.unixvoid.com/upload
